# Railway.toml para deploy do Frontend
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "always"
startCommand = "/start.sh"

[healthcheck]
path = "/health"
intervalSeconds = 30
timeoutSeconds = 10
retries = 3

# Environment variables
[env]
PORT = "3000"
NODE_ENV = "production"
