# Railway Configuration
# Each service uses its own specific Dockerfile

# Frontend Service (Node.js + nginx) - WORKING - DO NOT CHANGE
[services.frontend]
build.dockerfile = "frontend/Dockerfile"

# Backend Service (Python + FastAPI) - Complete dependencies version
[services.backend]
build.dockerfile = "Dockerfile.complete"
source = "backend"
