# Railway Configuration
# Each service uses its own specific Dockerfile
# Updated to force cache refresh - FORCE REBUILD NOW

# Frontend Service (Node.js + nginx)
[services.frontend]
build.dockerfile = "frontend/Dockerfile"

# Backend Service (Python + FastAPI) - Ultra minimal for debugging
[services.backend]
build.dockerfile = "Dockerfile.ultra-minimal"
source = "backend"
