# Configuração Railway para o projeto raiz
# Este arquivo define como deployar cada serviço
# Updated: Forcing redeploy with root context Dockerfile

# Frontend Service
[services.frontend]
build.dockerfile = "frontend/Dockerfile"

# Backend Service  
[services.backend]
build.dockerfile = "backend/Dockerfile.root-context"

# MEEP Service
[services.meep-service]
build.dockerfile = "meep-service/Dockerfile"
