# Railway Configuration
# Defines how to deploy each service

# Frontend Service
[services.frontend]
build.dockerfile = "frontend/Dockerfile"

# Backend Service (using minimal Dockerfile for reliability)
[services.backend]
build.dockerfile = "backend/Dockerfile.minimal"

# MEEP Service
[services.meep-service]
build.dockerfile = "meep-service/Dockerfile"
