# Railway configuration for Backend service
[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "always"

[healthcheck]
path = "/healthz"
intervalSeconds = 30
timeoutSeconds = 15
retries = 3

[env]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
