[phases.setup]
nixPkgs = ['python312', 'pip']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install fastapi[standard] uvicorn[standard] psycopg[binary] sqlalchemy alembic passlib[bcrypt] python-jose[cryptography] python-multipart pydantic-settings python-dotenv reportlab pandas qrcode pillow aiohttp websockets schedule openpyxl'
]

[phases.build]
cmds = [
  'python -c "from app.database import engine; from app.models import Base; Base.metadata.create_all(bind=engine)" || echo "Database setup will be done at runtime"'
]

[start]
cmd = 'python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT'