[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "always"
startCommand = "/app/start.sh"

[healthcheck]
path = "/healthz"
intervalSeconds = 30
timeoutSeconds = 15
retries = 3

[env]
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
